### ISSUE TITLE
Memory Leaking on "Capture Selection"

### ISSUE THREAD

**Issue by benjojo** [olav-st/screencloud#31] opened 2014-01-10 09:33 UTC
Each time (regardless if you complete the screenshot or not) you take a screenshot, it will allocate approx 10MB and never free it.

Windows 8  x86_64

Related to #28

**Comment by olav-st** [comment] 2015-12-17 12:46
Closing as a duplicate of https://github.com/olav-st/screencloud/issues/28.

**Closed by olav-st** 2015-12-17 12:46 UTC
Labels: bug, duplicate
