### ISSUE TITLE
Error when uploading to FTP

### ISSUE THREAD

**Issue by MelvinWesenhagen** [olav-st/screencloud#125] opened 2015-02-16 08:05 UTC
I got multiple errors when uploading using the FTP plugin i've added some screenshots of the errors.
Running windows 8.1 64bit with ScreenCloud version 1.2.0.
![scr1](https://cloud.githubusercontent.com/assets/10978126/6208589/e41aed12-b5ba-11e4-9483-4a9fb1a41e22.png)
![scr2](https://cloud.githubusercontent.com/assets/10978126/6208590/e420f4be-b5ba-11e4-9ed2-e0acea87cf0d.png)

**Comment by BoomLiam** [comment] 2015-02-16 14:16
I'm getting the same error, this is since the most recent update. Using Windows 8 64bit

**Comment by Jujo12** [comment] 2015-02-16 20:34
In screencloud FTP plugin, on line 69, a change should be made:
    ftp = ftplib.FTP(self.host, self.port)
to
    ftp = ftplib.FTP(self.host, int(self.port))

Until the fix is made, you can do it yourselves - the file is located in C:\Users\USERNAME\AppData\Local\screencloud\ScreenCloud\plugins\ftp\main.py

**Comment by BoomLiam** [comment] 2015-02-17 16:18
Hmm, still getting the same error :\

**Comment by Bak3y** [comment] 2015-02-17 16:19
Same error, in the path Jujo12 listed above, line 69 in main.py is already

ftp = ftplib.FTP(self.host, int(self.port))

**Comment by BoomLiam** [comment] 2015-02-17 16:21
Yeah, I do believe an update was rolled out today to address that change, but I think the issue is somewhere else :\ I dunno though, never touched Python myself :P

**Comment by Jujo12** [comment] 2015-02-17 16:40
Don't know, the bug seems fixed. Are you sure that you updated and that the exact same error appears?

**Comment by Bak3y** [comment] 2015-02-17 16:43
Running version 1.2.0.  Update checks show no update available.

The main.py file listed above has line 69 exactly as described and the error persists.

**Comment by Jujo12** [comment] 2015-02-17 16:52
Tried it right now, the error is back. However, when I revert to the old version, the error stays. Very strange. Will take a look into it, but don't promise anything. Hopefully, admins will know better.

**Comment by Bak3y** [comment] 2015-02-17 16:53
Casting the (self.port) as a str results in a different error, related to not being able to log in, however I know for a fact the username/password are correct.

Related, I also am seeing this error when trying to confirm my FTP settings.  
![ftperror](https://cloud.githubusercontent.com/assets/4029474/6232642/1b3272ce-b693-11e4-8217-64c2b74061a3.png)


It's almost like whatever file is saving the settings for FTP configs isn't being saved or read correctly.

**Comment by Jujo12** [comment] 2015-02-17 17:14
Found a fix. Proposing it to the admins right now, will link so you can download yourself.

**Comment by Jujo12** [comment] 2015-02-17 17:21
Here's the new main.py. Line 69 is the main change. However, I made some additional code cleaning (indentations and spaces).
https://github.com/Jujo12/screencloud-plugins/blob/master/ftp/main.py

**Comment by Bak3y** [comment] 2015-02-17 17:30
Works like a charm.  Thanks Jujo12!

**Comment by olav-st** [comment] 2015-02-17 17:42
I've merged @hTmlDP's pull request (https://github.com/olav-st/screencloud-plugins/pull/13) which also seems to fix the problem. Other improvements are still welcome though! :)

**Comment by C0kkie** [comment] 2015-02-17 17:44
i Try it...but already a error. did you update the plugin? can i download it?

**Comment by olav-st** [comment] 2015-02-17 17:45
Try restarting ScreenCloud. It should prompt you for an update.

**Comment by C0kkie** [comment] 2015-02-17 17:47
ok i have update it....but when i will create a screenshot -> screencloud crashed

**Comment by Jujo12** [comment] 2015-02-17 17:50
@olav-st, that solution is as legit, but a bit slower, since the FTP call connects during the initialization, not after. Both are valid, but I believe that submitting arguments to FTP class call is a bit better.

**Comment by BoomLiam** [comment] 2015-02-17 17:52
Yes, that has worked! Images are now being uploaded to the FTP server, but it seems to lag/freeze for a short period before copying the link to the clipboard, also the "ping" sound doesn't play when the link has been copied. Not too sure of the cause....

**Comment by KleinMuffin** [comment] 2015-02-17 17:52
sorry for being stupid but where do i put the files in?

**Comment by BoomLiam** [comment] 2015-02-17 17:54
Restarting your screencloud should prompt for an update, just let the update run. You shouldn't have to do anything manually :)

**Comment by KleinMuffin** [comment] 2015-02-17 17:56
Ah thank you :) That is working!

**Comment by hTmlDP** [comment] 2015-02-17 18:12
@Jujo12: As I said, python 2 doesn't support that [https://docs.python.org/2/library/ftplib.html#ftplib.FTP]. Also, it shouldn't be much faster - when you don't pass a hostname, it doesn't initialize any connection.

**Comment by MelvinWesenhagen** [comment] 2015-02-17 18:42
Well its working again!
Only the sound isnt playing anymore, but i think it will be fixed soon.
Thanks for the quick update!

**Comment by hTmlDP** [comment] 2015-02-17 18:47
@olav-st, are there any plugins in the TODO list?

**Comment by olav-st** [comment] 2015-02-17 19:08
@hTmlDP nope, but a google drive plugin has been requested: https://github.com/olav-st/screencloud/issues/124. Are you planning to write one?

**Closed** 2015-12-17 12:28 UTC
Labels: bug, plugins
