### ISSUE TITLE
No upload sound in 1.2.0

### ISSUE THREAD

**Issue by Zeluboba** [olav-st/screencloud#164] opened 2015-10-24 15:02 UTC
Hello,
after I've updated ScreenCloud to 1.2.0 from 1.0.6(probably) I don't get the sound when the screenshot is uploaded.

I'm on Windows. Didn't test with my Linux version.

**Comment by SerDIDG** [comment] 2015-11-26 21:39
Some for me on OSX 10.11

**Comment by olav-st** [comment] 2015-12-17 12:20
Duplicate of https://github.com/olav-st/screencloud/issues/131.

**Closed by olav-st** 2015-12-17 12:20 UTC
Labels: bug
