### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by normanfeltz** [olav-st/screencloud#95] opened 2014-08-21 23:24 UTC
Hello,
You can add a system to save screenshot in local, clipboard.
A system for mask things on image or even a system that would allow us to show in detail.

 ![Image](http://st.prntscr.com/2014/08/11/1026/img/media-screen-1.jpg)

A system for creating video gif
 
 ![Image](http://3.bp.blogspot.com/-Cf0K9O9xceM/UvoTauuOy4I/AAAAAAAAV9E/O0ZpR3k5yCU/s1600/Screentogif.jpg)

Cordialy

Norman FELTZ

**Comment by olav-st** [comment] 2015-12-17 11:54
Closing, since clipboard and editing is available now, and gif support is a duplicate of this https://github.com/olav-st/screencloud/issues/112.

**Closed by olav-st** 2015-12-17 11:54 UTC
Labels: enhancement
