### ISSUE TITLE
Icon invisible on dark status bar, doesn't get greyed out if other display is active on Mac OS X

### ISSUE THREAD

**Issue by niklaswa** [olav-st/screencloud#311] opened 2018-02-17 18:42 UTC
On bright theme _(while I'm at it, it would be pretty nice if the icon would be more gray too)_:
![bright](https://user-images.githubusercontent.com/7442307/36344422-49baede6-141a-11e8-8905-69ad8aaf137c.png)
On dark theme:
![dark](https://user-images.githubusercontent.com/7442307/36344394-fed8ff20-1419-11e8-9e12-e8af173b4789.png)
[Aaaand... if a window on another display is focused, the icon doesn't get greyed out:]
![unfocused](https://user-images.githubusercontent.com/7442307/36344435-8002db5c-141a-11e8-9e58-af521ee098ea.png)

**Comment by niklaswa** [comment] 2018-02-17 18:44
Rel: #252 #280

**Comment by olav-st** [comment] 2019-06-30 09:04
Closing as a duplicate of https://github.com/olav-st/screencloud/issues/152, which has now been fixed.

**Closed by olav-st** 2019-06-30 09:04 UTC
Labels: duplicate, enhancement, mac-specific
