### ISSUE TITLE
Add new files saved with Local File plugin into Recently Used documents list

### ISSUE THREAD

**Issue by stuartlangridge** [olav-st/screencloud#167] opened 2015-11-17 18:45 UTC
Gtk provides an API, https://developer.gnome.org/gtk3/stable/GtkRecentManager.html#gtk-recent-manager-add-item, to add a recently used file to the recently used file list. It would be great if the Local File plugin for Screencloud used this on Linux, so that a locally saved file can be easily retrieved from Recent rather than having to navigate to the chosen folder and find the file by name.

**Comment by olav-st** [comment] 2015-12-17 12:17
Duplicate of https://github.com/olav-st/screencloud/issues/111.

**Closed by olav-st** 2015-12-17 12:17 UTC
Labels: enhancement
